package orderHandler

import (
	cons "backend/constants"
	"backend/structs"
	. "backend/structs"
	utility "backend/utility"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/jmoiron/sqlx"
)

/*
OrdersHandler supports the following methods:
- GET: Fetches a specific order by ID.
- PUT: Updates an existing order.

# GET

GET handles the retrieval of all orders from the database.
It queries the database for all orders and returns them as a JSON response.
It does not respond with the orders items.

Only admin users can access this endpoint.

Example usage:

	Method: GET
	Route: /orders
	Response:
	[
		{
			"order_id": "12345",
			"user_id": "67890",
			"order_date": "2023-10-01T12:00:00Z",
			"order_status": "Pending",
			"order_total": 100.50
			"items": null
		},
		{
			"order_id": "54321",
			"user_id": "09876",
			"order_date": "2023-10-02T12:00:00Z",
			"order_status": "Shipped",
			"order_total": 200.75
			"items": null
		}
	]

# POST

POST handles the creation of a new order in the database.
It expects a JSON payload with the order details, in JSON format.
The order ID is generated by the database, and the new order is inserted into the database.

# To add items to the order, a

Mandatory fields cannot be null, while optional can be null.

The request body should contain the following fields:

	{
	- user_id	(string)| mandatory	: The ID of the user placing the order.
	- order_date	(string)| optional	: The date of the order in ISO 8601 format.
	- order_total	(float64)| mandatory	: The total amount of the order.
	- order_status	(string)| mandatory	: The status of the order, must be found in the OrderStatus table.
	- items	(array of objects)| optional	: The order_items in the order. Each item must contain the product ID and quantity. See below for the format.

		The order items should contain the following fields:
		{
		- product_id	(string)| mandatory	: The ID of the product.
		- quantity		(int)| mandatory	: The quantity of the product.
		}
	}

Example usage:

	Method: POST
	Route: /orders
	Request Body:
	{
		"user_id": "67890",
		"order_date": "2023-10-01T12:00:00Z",
		"order_status": "Pending",
		"order_total": 100.50,
		"items": [
			{
				"product_id": "54321",
				"quantity": 2
			},
			{
				"product_id": "67890",
				"quantity": 1
			}
		]
	}
	Response:
	Http Status: 201 Created
	{
		"id": "12345"
	}
*/
func OrdersHandler(w http.ResponseWriter, r *http.Request) {
	log.Println("OrdersHandler called with method: ", r.Method)
	switch r.Method {
	case http.MethodGet:
		// Check admin privileges
		if !utility.CheckPrivileges(r, w, nil) {
			return
		}

		var orders []Order
		err := cons.DB.Select(&orders, cons.QueryOrders)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error fetching orders: ", err)
			http.Error(w, "Error fetching orders", http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(orders); err != nil {
			log.Println("Error encoding orders to JSON: ", err)
			http.Error(w, "Error encoding orders to JSON", http.StatusInternalServerError)
			return
		}

	case http.MethodPost:
		var order structs.Order
		if err := json.NewDecoder(r.Body).Decode(&order); err != nil {
			log.Println("Error decoding order: ", err)
			http.Error(w, "Error decoding order", http.StatusBadRequest)
			return
		}

		// Generate a new product ID
		err := cons.DB.Get(&order, "SELECT UUID() AS "+cons.ORDER_ID+";")
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}

			log.Println("Error generating order ID: ", err)
			http.Error(w, "Error generating order ID", http.StatusInternalServerError)
			return
		}
		log.Println("Order ID: ", order.OrderID)
		id := order.OrderID

		transactError := utility.Transact(func(tx *sqlx.Tx) error {
			_, err = tx.NamedExec(cons.InsertOrder, order)
			if err != nil {
				return err
			}
			for _, item := range order.Items {
				item.OrderID = id
				_, err = tx.NamedExec(cons.InsertOrderItem, item)
				if err != nil {
					return err
				}
			}

			return nil // no errors! :D
		})

		if transactError != nil {
			if utility.CheckSQLErr(transactError, w) {
				return
			}
			log.Println("Error inserting order: ", transactError)
			http.Error(w, "Error inserting order", http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		// Return the ID of the newly created product
		response := map[string]string{"id": id}
		if err := json.NewEncoder(w).Encode(response); err != nil {
			log.Println("Error encoding order to JSON: ", err)
			http.Error(w, "Error encoding order to JSON", http.StatusInternalServerError)
			return
		}

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

/*
OrderHandler supports the following methods:
- GET: Fetches a specific order by ID.
- PUT: Updates an existing order.
- PATCH: Partially updates an existing order.
- DELETE: Deletes an existing order.

# GET

GET handles the retrieval of a specific order by ID from the database.
It queries the database for the order with the specified ID and returns it as a JSON response.
It also fetches the order items associated with that order and includes them in the response.

Example usage:

	Method: GET
	Route: /orders/12345
	Response:
	Http Status: 200 OK
	{
		"order_id": "12345",
		"user_id": "67890",
		"order_date": "2023-10-01T12:00:00Z",
		"order_status": "Pending",
		"order_total": 100.50,
		"items": [
			{
				"order_id": "12345",
				"product_id": "54321",
				"quantity": 2
			},
			{
				"order_id": "12345",
				"product_id": "67890",
				"quantity": 1
			}
		]
	}

# PUT

PUT handles the update of an existing order in the database.
It expects a JSON payload with the order details, in JSON format.
The order ID is specified in the URL, and the order details are provided in the request body.

Items associated with the order cannot be updated in this request.
User ID and Order ID cannot be changed.

Mandatory fields cannot be null, while optional can be null.

The request body should contain the following fields:

	{
	- order_date	(string)| optional	: The date of the order in ISO 8601 format.
	- order_total	(float64)| mandatory	: The total amount of the order.
	- order_status	(string)| mandatory	: The status of the order. Must be a status found in the OrderStatus table.
	}

Example usage:

	Method: PUT
	Route: /orders/12345
	Request Body:
	{
		"order_date": "2023-10-01T12:00:00Z",
		"order_status": "Pending",
		"order_total": 100.50
	}
	Response:
	Http Status: 200 OK

# PATCH

PATCH handles the partial update of an existing order in the database.
The order ID is specified in the URL, and the order details are provided in the request body.

The request body can use any field(s) available in the PUT method, in the same format.

Mandatory fields cannot be null, while optional can be null.

# DELETE

DELETE handles the deletion of an existing order in the database.
It expects the order ID to be specified in the URL.
The order is deleted from the database, and a 204 No Content response is returned.

Example usage:

	Method: DELETE
	Route: /orders/12345
	Response:
	Http Status: 204 No Content
*/
func OrderHandler(w http.ResponseWriter, r *http.Request) {
	log.Println("OrderHandler called with method : ", r.Method)
	switch r.Method {
	case http.MethodGet:
		orderID := r.PathValue("order_id")

		var order Order

		err := cons.DB.Get(&order, cons.QueryOrder, orderID)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error fetching order: ", err)
			http.Error(w, "Error fetching order", http.StatusInternalServerError)
			return
		}

		var orderItems []OrderItem
		err = cons.DB.Select(&orderItems, cons.QueryOrderItemsByID, orderID)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error fetching order items: ", err)
			http.Error(w, "Error fetching order items", http.StatusInternalServerError)
			return
		}
		order.Items = orderItems
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(order); err != nil {
			log.Println("Error encoding order to JSON: ", err)
			http.Error(w, "Error encoding order to JSON", http.StatusInternalServerError)
			return
		}

	case http.MethodPut:
		id := r.PathValue("order_id")
		if id == "" {
			log.Println("Order ID is required for PUT request")
			http.Error(w, "Order ID is required", http.StatusBadRequest)
			return
		}

		var order Order
		if err := json.NewDecoder(r.Body).Decode(&order); err != nil {
			log.Println("Error decoding order: ", err)
			http.Error(w, "Error decoding order", http.StatusBadRequest)
			return
		}
		if order.OrderID != "" && order.OrderID != id {
			http.Error(w, "Order ID cannot be changed", http.StatusBadRequest)
			return
		}
		if order.UserID != "" {
			http.Error(w, "User ID cannot be changed", http.StatusBadRequest)
			return
		}
		order.OrderID = id

		// check for mandatory fields
		if order.OrderTotal == 0 || order.OrderStatus == "" {
			log.Println("Mandatory fields are missing")
			http.Error(w, "Mandatory fields are missing", http.StatusBadRequest)
			return
		}

		log.Println("Order : ", order)

		// Update the order in the database
		_, err := cons.DB.NamedExec(cons.UpdateOrder, order)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error updating order: ", err)
			http.Error(w, "Error updating order", http.StatusInternalServerError)
			return
		}
		log.Println("Order updated successfully with ID: ", order.OrderID)
		w.WriteHeader(http.StatusOK)

	case http.MethodPatch:
		id := r.PathValue("order_id")
		if id == "" {
			log.Println("Order ID is required for PATCH request")
			http.Error(w, "Order ID is required", http.StatusBadRequest)
			return
		}
		var orderPatch OrderPatch
		if err := json.NewDecoder(r.Body).Decode(&orderPatch); err != nil {
			log.Println("Error decoding order patch: ", err)
			http.Error(w, "Error decoding order patch", http.StatusBadRequest)
			return
		}
		if orderPatch.OrderID != "" && orderPatch.OrderID != id {
			http.Error(w, "Order ID cannot be changed", http.StatusBadRequest)
			return
		}
		orderPatch.OrderID = id

		query := "UPDATE " + cons.ORDER_TABLE + " SET "

		setClause, args := utility.BuildUpdateQuery(orderPatch)
		if setClause == "" {
			log.Println("No fields to update")
			http.Error(w, "No fields to update", http.StatusBadRequest)
			return
		}
		query += setClause + " WHERE " + cons.ORDER_ID + " = ?"
		args = append(args, id)
		// Log the query for debugging
		log.Println("Executing query: ", fmt.Sprintf(strings.ReplaceAll(query, "?", "%s"), args...))

		_, err := cons.DB.Exec(query, args...)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error updating order: ", err)
			http.Error(w, "Error updating order", http.StatusInternalServerError)
			return
		}
		log.Println("Order updated successfully with ID: ", orderPatch.OrderID)
		w.WriteHeader(http.StatusOK)

	case http.MethodDelete:
		id := r.PathValue("order_id")
		if id == "" {
			log.Println("Order ID is required for DELETE request")
			http.Error(w, "Order ID is required", http.StatusBadRequest)
			return
		}

		// Delete the order from the database
		result, err := cons.DB.Exec(cons.DeleteOrder, id)
		if err != nil {
			if utility.CheckSQLErr(err, w) {
				return
			}
			log.Println("Error deleting order: ", err)
			http.Error(w, "Error deleting order", http.StatusInternalServerError)
			return
		}

		if utility.CheckDeleteResult(result, w) {
			return
		}

		log.Println("Order deleted successfully with ID: ", id)
		// Return a 204 No Content response
		w.WriteHeader(http.StatusNoContent)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}
