CREATE TABLE Category (
    CategoryName VARCHAR(50) NOT NULL PRIMARY KEY,
    CategoryDesc VARCHAR(255)
);

CREATE TABLE Brand (
    BrandName VARCHAR(50) NOT NULL PRIMARY KEY,
    BrandDesc VARCHAR(255)
);

CREATE TABLE Product (
    ProductID VARCHAR(50) NOT NULL PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    ProductDesc VARCHAR(255),
    ProductImgUrl VARCHAR(255),
    Price DECIMAL(10,2) NOT NULL,
    StockQuantity INT NOT NULL,
    Brand VARCHAR(50),
    Category VARCHAR(50),
    FOREIGN KEY (Brand) REFERENCES Brand(BrandName) ON UPDATE CASCADE,
    FOREIGN KEY (Category) REFERENCES Category(CategoryName) ON UPDATE CASCADE
);

CREATE TABLE Users (
    UserID VARCHAR(50) NOT NULL PRIMARY KEY,
    Username VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Address VARCHAR(255)
);

CREATE TABLE Member (
    UserID VARCHAR(50) PRIMARY KEY,
    MembershipLevel ENUM('Silver', 'Gold', 'Platinum') NOT NULL,
    MembershipStart DATE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE OrderStatus (
    StatusName VARCHAR(50) NOT NULL PRIMARY KEY,
    StatusDesc VARCHAR(255)
);

CREATE TABLE OrderTable (
    OrderID VARCHAR(50) NOT NULL PRIMARY KEY,
    UserID VARCHAR(50) NOT NULL,
    OrderDate DATE,
    OrderStatus VARCHAR(50) NOT NULL,
    OrderTotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON UPDATE CASCADE,
    FOREIGN KEY (OrderStatus) REFERENCES OrderStatus(StatusName) ON UPDATE CASCADE
);

CREATE TABLE OrderItem (
    OrderID VARCHAR(50) NOT NULL,
    ProductID VARCHAR(50) NOT NULL,
    Quantity INT NOT NULL,
    PRIMARY KEY (OrderID, ProductID),
    FOREIGN KEY (OrderID) REFERENCES OrderTable(OrderID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON UPDATE CASCADE
);

CREATE TABLE Payment (
    PaymentID VARCHAR(50) NOT NULL PRIMARY KEY,
    OrderID VARCHAR(50) NOT NULL,
    PaymentMethod ENUM('card', 'vipps', 'bank_transfer') NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentDate DATE NOT NULL,
    PaymentStatus ENUM('pending', 'successful', 'failed'),
    FOREIGN KEY (OrderID) REFERENCES OrderTable(OrderID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CartItem (
    UserID VARCHAR(50) NOT NULL,
    ProductID VARCHAR(50) NOT NULL,
    Quantity INT,
    PRIMARY KEY (UserID, ProductID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON UPDATE CASCADE
);

CREATE TABLE Review (
    UserID VARCHAR(50) NOT NULL,
    ProductID VARCHAR(50) NOT NULL,
    Comment VARCHAR(500),
    Rating INT CHECK (Rating BETWEEN 1 AND 10),
    PostDate DATE NOT NULL,
    PRIMARY KEY (UserID, ProductID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON UPDATE CASCADE ON DELETE CASCADE
);